### PR TITLE
Fix #8822: Some procedures containing LIST aggregate function are not restored in Firebird 6.0

### LINKED ISSUE #8822: Backward compatibility: Some procedures containing LIST aggregate function are not restored in Firebird 6.0 if backup was made in 5.0
Let's create the following stored procedure in a Firebird 5.0 database.

```sql
SET TERM ^;

CREATE OR ALTER PROCEDURE SOME_PROC (
  PRIVATE_FLAG SMALLINT)
RETURNS (
  PACKAGE_NAME VARCHAR(63),
  TEXT         BLOB SUB_TYPE TEXT)
AS
BEGIN
  FOR
    WITH
      T AS (
        SELECT
          P.RDB$PACKAGE_NAME || '' AS PACKAGE_NAME,
          LIST(DISTINCT P.RDB$PROCEDURE_NAME, '; ') AS PROCEDURE_NAME
        FROM RDB$PROCEDURES P
        WHERE RDB$PRIVATE_FLAG = :PRIVATE_FLAG
        GROUP BY 1
        ORDER BY 1
      )
    SELECT
      COALESCE(PACKAGE_NAME, '') AS PACKAGE_NAME,
      PROCEDURE_NAME
    FROM T
    INTO PACKAGE_NAME, TEXT
  DO
    SUSPEND;
END^

SET TERM ;^
```

Now let's perform a backup of the database.

```
gbak -b -g test.fdb test.fbk
```

Next, we will try to restore it in Firebird 6.0.

```
gbak -c test.fbk test.fdb
```

During the database restore process we receive the following error.

```
gbak: ERROR:Error while parsing procedure "PUBLIC"."SOME_PROC"'s BLR
gbak: ERROR:    bad BLR -- invalid stream
gbak: ERROR:    Exiting before completion due to errors
gbak:Exiting before completion due to errors
```

### PR DESCRIPTION
**Pull request by dyemanov**
Since a new BLR verb is required anyway, I've added just one (for custom order) instead of duplicating both `blr_agg_list_*` verbs.

Also, the BLR printer is extended to support (optionally) `WITHIN GROUP` clause in other aggregate functions.

Once merged, `PERCENTILE_CONT` and `PERCENTILE_DISC` functions (PR #8807) should also be changed to utilize `blr_within_group_order`.

### CODE REVIEW

**Comment by dyemanov** [comment]
BLR output after the patch, for the `COUNT` / legacy `LIST` / ordered `LIST`:

```
1,0,
blr_agg_count_distinct,
    blr_field, 0, 18, 'R','D','B','$','P','R','O','C','E','D','U','R','E','_','N','A','M','E',
2,0,
blr_agg_list_distinct,
    blr_field, 0, 18, 'R','D','B','$','P','R','O','C','E','D','U','R','E','_','N','A','M','E',
    blr_literal, blr_text2, 0,0, 2,0, 59,32,
3,0,
blr_agg_list_distinct,
    blr_field, 0, 18, 'R','D','B','$','P','R','O','C','E','D','U','R','E','_','N','A','M','E',
    blr_literal, blr_text2, 0,0, 2,0, 59,32,
    blr_within_group_order, 1,
        blr_ascending,
            blr_field, 0, 18, 'R','D','B','$','P','R','O','C','E','D','U','R','E','_','N','A','M','E',
```

File: src/jrd/blp.h [hunk 1]
```diff
@@ -267,5 +267,6 @@ static inline constexpr struct
 	{"default2", default2},
 	{"current_schema", zero},
 	{NULL, NULL},	// flags - part of header
+	{NULL, NULL},
```
Comment (asfernandes) [inline src/jrd/blp.h]: This should have a comment about blr_within_group_order as normally every main code is there.
