### PR TITLE
Fixed bug #8168 : MAKE_DBKEY bug after backup/restore

### LINKED ISSUE #8168: MAKE_DBKEY bug after backup/restore
Firebird relation ids are not stable. While some BLRs uses relation ids, BLR of stored code always refers to them by name.

However, system function `MAKE_DBKEY` transforms relation name to id and stores this id even in stored BLR.

After backup/restore, `MAKE_DBKEY(name)` is going to refer to different table.

### PR DESCRIPTION
**Pull request by hvlad**

### CODE REVIEW

File: src/dsql/ExprNodes.cpp [hunk 1]
```diff
@@ -12297,6 +12297,30 @@ DmlNode* SysFuncCallNode::parse(thread_db* tdbb, MemoryPool& pool, CompilerScrat
...
+	{
+		// Special handling for system function MAKE_DBKEY:
+		// convert constant relation name into ID at the parsing time
+
+		auto literal = nodeAs<LiteralNode>(node->args->items[0]);
+
+		if (literal && literal->litDesc.isText())
+		{
+			const MetaName relName = literal->getText();
+			const jrd_rel* const relation = MET_lookup_relation(tdbb, relName);
```
Comment (asfernandes) [inline src/dsql/ExprNodes.cpp:12310]: Shouldn't also better register a dependency on the relation?

Comment (hvlad) [reply src/dsql/ExprNodes.cpp:12310]: The function itself makes no actions with relation. All it needs - know relation ID.
Thus, I don't think we need any kind of dependency here.

Comment (asfernandes) [reply src/dsql/ExprNodes.cpp:12310]: I understand, but if one drops a relation directly referenced by name inside a given procedure, next time this procedure will not be loaded. Dependencies exists just to avoid that.

Comment (hvlad) [reply src/dsql/ExprNodes.cpp:12310]: I still see no need in dependency - it is too restrictive in this case. 
I'll better raise error at the execution phase, if relation was not found at parse time.

Comment (dyemanov) [reply src/dsql/ExprNodes.cpp:12310]: In this function the relation name is a literal, not an identifier. Thus I agree a dependency is not needed, a runtime check looks enough.

**Review by asfernandes — APPROVED** [review]
