### PR TITLE
Fix for #8105:  Master database could miss replication segments on Windows Classic Server

### LINKED ISSUE #8105: Master database could miss replication segments on Windows Classic Server
When Firebird run on Windows and configured as Classic Server it could not generate some replcation segments.
Segments numbers could be, for example 1,3,5,7, etc.
Also, it could create more files in `journal_directory` than it is allowed by `journal_segment_count`

### PR DESCRIPTION
**Pull request by hvlad**
The main problem is that on Windows it is not allowed to rename open files with mapped memory section.
`rename()` for such file always set `errno` to `EACCES`, `GetLastError()` returns `ERROR_SHARING_VIOLATION`.

### CODE REVIEW

File: src/jrd/replication/ChangeLog.cpp [hunk 1]
```diff
@@ -950,11 +1003,26 @@ ChangeLog::Segment* ChangeLog::reuseSegment(ChangeLog::Segment* segment)
...
 		return createSegment();
+	}
 
 	// Re-open the segment using a new name and initialize it
 
 	const auto fd = os_utils::openCreateSharedFile(newname.c_str(), O_BINARY);
+	if (fd == -1)
+	{
+		raiseError("Journal file %s create() failed (error %d)", newname.c_str(), errno);
+	}
```
Comment (dyemanov) [inline src/jrd/replication/ChangeLog.cpp:1026]: `openCreateSharedFile()` throws itself, so this addition is not necessary.

File: src/jrd/replication/ChangeLog.cpp [hunk 2]
```diff
@@ -893,13 +941,17 @@ void ChangeLog::clearSegments()
...
 
 	PathName filename;
 	filename.printf(FILENAME_PATTERN, m_config->filePrefix.c_str(), sequence);
 	filename = m_config->journalDirectory + filename;
 
 	const auto fd = os_utils::openCreateSharedFile(filename.c_str(), O_EXCL | O_BINARY);
+	if (fd == -1)
+	{
+		raiseError("Journal file %s create() failed (error %d)", filename.c_str(), ERRNO);
+	}
```
Comment (dyemanov) [inline src/jrd/replication/ChangeLog.cpp:954]: openCreateSharedFile() throws itself, so this addition is not necessary.

Comment (hvlad) [reply src/jrd/replication/ChangeLog.cpp]: Done, thanks

File: src/jrd/replication/ChangeLog.cpp (hunk 1 above)
Comment (hvlad) [reply src/jrd/replication/ChangeLog.cpp]: Done

**Review by dyemanov — APPROVED** [review]
