### PR TITLE
Fixed bug #7873 : Wrong memory buffer alignment and IO buffer size when working in direct IO mode

### LINKED ISSUE #7873: Wrong memory buffer alignment and IO buffer size when working in direct IO mode
Customer reports that nbackup issues error when backup database:

IO error reading file: database.fdb
The parameter is incorrect. 

Investigation shows that:
1. The OS is Windows,
2. error happens with direct IO ON only (switch -D ON), 
3. volume where database file reside have following properties (I show important ones only):

Bytes Per Sector  :                4096
Bytes Per Physical Sector :        4096

### PR DESCRIPTION
**Pull request by hvlad**
This PR is based on #7874 and #241

### CODE REVIEW

File: src/common/classes/array.h [hunk 1]
```diff
@@ -425,6 +425,16 @@ class Array : protected Storage
 		return data;
 	}
 
+	// prepare array to be used as a buffer of capacity bytes aligned on given alignment
+	T* getAlignedBuffer(const size_type capacityL, const size_type alignL)
+	{
+		static_assert(sizeof(T) == 1, "sizeof(T) != 1");
+
+		ensureCapacity(capacityL + alignL, false);
```
Comment (aafemt) [inline src/common/classes/array.h:433]: I think that `- ALLOC_ALIGNMENT` can be added here to reduce memory overhead a little.

Comment (aafemt) [reply src/common/classes/array.h:433]: AFAIU your code add some unused space at the beginning and the end of allocated buffer to get right alignment. Because allocated raw buffer already aligned, the difference between raw buffer pointer and returning buffer pointer is guaranteed to be smaller than `alignL` at least by ALLOC_ALIGNMENT (actually ALLOC_ALIGNMENT + 1) bytes, so unused space at the end can be safely reduced.

Comment (hvlad) [reply src/common/classes/array.h:433]: > AFAIU your code add some unused space at the beginning and the end of allocated buffer to get right alignment. Because allocated raw buffer already aligned, the difference between raw buffer pointer and returning buffer pointer is guaranteed to be smaller than `alignL` at least by ALLOC_ALIGNMENT (actually ALLOC_ALIGNMENT + 1) bytes, so unused space at the end can be safely reduced.

Formally you right, but how mush you going to save ? 16 bytes of few KBs ?

File: src/jrd/jrd.cpp [hunk 2]
```diff
@@ -7592,11 +7592,17 @@ static JAttachment* create_attachment(const PathName& alias_name,
...
 static void check_single_maintenance(thread_db* tdbb)
 {
-	UCHAR spare_memory[RAW_HEADER_SIZE + PAGE_ALIGNMENT];
-	UCHAR* header_page_buffer = FB_ALIGN(spare_memory, PAGE_ALIGNMENT);
+	Database* const dbb = tdbb->getDatabase();
+
+	const ULONG ioBlockSize = dbb->getIOBlockSize();
+	const ULONG headerSize = MAX(RAW_HEADER_SIZE, ioBlockSize);
+
+	HalfStaticArray<UCHAR, RAW_HEADER_SIZE + PAGE_ALIGNMENT> temp;
```
Comment (asfernandes) [inline src/jrd/jrd.cpp:7600]: Here you used HalfStaticArray with fixed alignments, not using the mechanism of its Align parameter and using the base `getAlignedBuffer`. That's the place I'm saying it's better to change HalfStaticArray and use it normally.

File: src/common/classes/array.h (hunk 1 above)
Comment (hvlad) [reply src/common/classes/array.h:433]: Do you really think that every page buffer in page cache is allocated separately ?

File: src/utilities/gstat/dba.epp [hunk 3]
```diff
@@ -612,9 +612,9 @@ int gstat(Firebird::UtilSvc* uSvc)
 
 	dba_fil* current = db_open(fileName.c_str(), fileName.length());
 
-	SCHAR temp[RAW_HEADER_SIZE];
-	tddba->page_size = sizeof(temp);
-	tddba->global_buffer = (pag*) temp;
+	SCHAR temp[RAW_HEADER_SIZE + DIRECT_IO_BLOCK_SIZE];
```
Comment (asfernandes) [inline src/utilities/gstat/dba.epp:615]: You can use `alignas(DIRECT_IO_BLOCK_SIZE)` here.

File: src/jrd/CryptoManager.h [hunk 4]
```diff
@@ -312,16 +312,16 @@ class CryptoManager final : public Firebird::PermanentStorage, public BarSync::I
...
 
 		Ods::pag* operator->()
 		{
-			return reinterpret_cast<Ods::pag*>(FB_ALIGN(buf, PAGE_ALIGNMENT));
+			return reinterpret_cast<Ods::pag*>(FB_ALIGN(buf, DIRECT_IO_BLOCK_SIZE));
 		}
 
 	private:
-		char buf[MAX_PAGE_SIZE + PAGE_ALIGNMENT - 1];
+		char buf[MAX_PAGE_SIZE + DIRECT_IO_BLOCK_SIZE];
```
Comment (asfernandes) [inline src/jrd/CryptoManager.h:324]: You can use `alignas(DIRECT_IO_BLOCK_SIZE)` here.

File: src/common/classes/array.h (hunk 1 above)
Comment (aafemt) [reply src/common/classes/array.h:433]: > Do you really think that every page buffer in page cache is allocated separately ?

Probably I'm wrong but yes, I do.

Comment (asfernandes) [reply src/common/classes/array.h:433]: We're talking about generic code in common, so I support the idea of optimize it for general use case.

File: src/jrd/jrd.cpp (hunk 2 above)
Comment (hvlad) [reply src/jrd/jrd.cpp:7600]: The actual alignment could be different (bigger) than used in template, thus I don't see what changes in HalfStaticArray could make the code better or more efficient.

File: src/common/classes/array.h (hunk 1 above)
Comment (aafemt) [reply src/common/classes/array.h:433]: Ok. In any case the difference can be found on https://firebirdtest.com/oltp-emul/ if someone add this branch there.

File: src/utilities/gstat/dba.epp (hunk 3 above)
Comment (hvlad) [reply src/utilities/gstat/dba.epp]: Done

File: src/jrd/CryptoManager.h (hunk 4 above)
Comment (hvlad) [reply src/jrd/CryptoManager.h]: Done

File: src/common/classes/array.h (hunk 1 above)
Comment (hvlad) [reply src/common/classes/array.h:433]: > We're talking about generic code in common, so I support the idea of optimize it for general use case.

Sorry, I see any real benefits here but code complication.
Feel free to add such optimization outside of this PR.

**Review by dyemanov — APPROVED** [review]
