### PR TITLE
The part of fix #7599. Problems with pointers in decNumber library

### LINKED ISSUE #7599: Conversion of text with '\0' to DECFLOAT without errors.
```
SQL> show version;
ISQL Version: WI-V4.0.3.2937 Firebird 4.0
Server version:
Firebird/Windows/AMD/Intel/x64 (access method), version "WI-V4.0.3.2937 Firebird 4.0"
Firebird/Windows/AMD/Intel/x64 (remote server), version "WI-V4.0.3.2937 Firebird 4.0/tcp (HOME4)/P17:C"
Firebird/Windows/AMD/Intel/x64 (remote interface), version "WI-V4.0.3.2937 Firebird 4.0/tcp (HOME4)/P17:C"
on disk structure version 13.0
SQL> select cast('123'||x'00'||'321' as integer) from rdb$database;

        CAST
============
Statement failed, SQLSTATE = 22018
conversion error from string "123"
SQL> select cast('123'||x'00'||'321' as DECFLOAT(34)) from rdb$database;

                                      CAST
==========================================
                                       123

```

### PR DESCRIPTION
**Pull request by dmitry-lipetsk**
This change corrects two problems in decNumber library those were described in #7599.

1. The incorrect ignorance of leading zeros in decFloatFromString function
2. The bad scope of a local buffer in decFinalize function

Both problems can lead to work with bad memory pointers.

### CODE REVIEW

File: extern/decNumber/decCommon.c [hunk 1]
```diff
@@ -254,6 +255,8 @@ static decFloat * decFinalize(decFloat *df, bcdnum *num,
   // decShowNum(num, "final");
   #endif
 
+  assert(umsd<=ulsd);
```
Comment (AlexPeshkoff) [inline extern/decNumber/decCommon.c:258]: I see you've decided to use assert()?

Comment (dmitry-lipetsk) [reply extern/decNumber/decCommon.c:258]: Yes. I thought - a porridge can't be spoilt with butter.

Comment (dmitry-lipetsk) [reply extern/decNumber/decCommon.c:258]: Do you run tests with the debug build of server?

Comment (aafemt) [reply extern/decNumber/decCommon.c:258]: Standard assert() used to write message to stdout so for Firebird it worse than useless: stdout is redirected to network stream in Classic mode.

Comment (asfernandes) [reply extern/decNumber/decCommon.c]: Standard `assert`, as a standard thing, is used in every project that do not want to rewrite the standard, like all libraries we use: re2, libcds, decNumber, etc. So why not? I'd say the changes to decNumber must use (this very ugly) decNumber's code style and must be redirected to some of its project who claims to be the "official" one.

Comment (AlexPeshkoff) [reply extern/decNumber/decCommon.c]: > Do you run tests with the debug build of server?

Not on the regular basis.

**Comment by dmitry-lipetsk** [comment]
It is need to do the equal PR for HEAD (master)?

**Comment by AlexPeshkoff** [comment]
Depends on your desire. I can easily front-port it myself.

**Comment by AlexPeshkoff** [comment]
Done. And I return to old question - do you wish to contact IBM yourself?

**Comment by dmitry-lipetsk** [comment]
>do you wish to contact IBM yourself?

No, thanks :)
