### PR TITLE
Fixed #7579: Cannot nbackup a firebird 3.0 database in firebird 4.0 service with engine12 setup in Providers

### LINKED ISSUE #7579: Cannot nbackup a firebird 3.0 database in firebird 4.0 service with engine12 setup in Providers
In firebird 4.0, I configure `firebird.conf` to support both `engine12` and `engine13` plugins:

    Providers = Remote,Engine13,Engine12,Loopback

The firebird service may access both Firebird 3.0 and 4.0 database.

Next, I try to nbackup a Firebird 4.0 employee database and it works:

    fbsvcmgr service_mgr action_nbak dbname c:\4.0\employee.fdb nbk_file r:\fb40.nb0 nbk_level 0

Finally, I try to use nbackup a Firebird 3.0 employee database:

    fbsvcmgr service_mgr action_nbak dbname c:\3.0\employee.fdb nbk_file r:\fb30.nb0 nbk_level 0

and it fail with message:

    unsupported on-disk structure for file c:\3.0\employee.fdb; found 12.0, support 13.0

### PR DESCRIPTION
**Pull request by AlexPeshkoff**
In my environment the following commit in B3_0_Release is needed to make engine12 use ICU already loaded before it by engine13: https://github.com/FirebirdSQL/firebird/commit/2052fde1f2138859eb03da6d782edbfa50a879dd
It has nothing to do with provider selection, just not backported earlier fix for mod_loader.

For me after applying this PR commands:
```
fbsvcmgr localhost: user sysdba password masterkey action_nbak dbname e12 nbk_file e12copy nbk_level 0
fbsvcmgr localhost: user sysdba password masterkey action_db_stats sts_hdr_pages dbname e12
```
work fine with FB5 server and the following config:
firebird.conf:
`Providers = Remote,Engine13,Engine12,Loopback`
databases.conf:
`e12 = $(dir_sampleDb)/e12.fdb`
where e12.fdb has ODS major == 12.

### CODE REVIEW

File: src/yvalve/why.cpp [hunk 1]
```diff
@@ -6320,6 +6321,43 @@ void YService::start(CheckStatusWrapper* status, unsigned int spbLength, const u
...
+				{
+					alternativeHandle->start(&st, spb.getBufferLength(), spb.getBuffer());
+					if (st.isSuccess())
+					{
+						status->init();
+						return;
+					}
+				}
+
+				// we are not going to attach network providers, therefore const svcName is OK
```
Comment (aafemt) [inline src/yvalve/why.cpp:6343]: Actually - why? What's wrong with remote providers running service on different (local) server if engine cannot handle this database? I can easily imagine configuration "Providers=Engine13,loopback" and Firebird 3 installed as well.

File: src/include/firebird/FirebirdInterface.idl [hunk 2]
```diff
@@ -734,6 +734,10 @@ version:	// 3.0.9 => 3.0.10, 4.0.1 => 4.0.2
 
 interface Provider : PluginBase
 {
+	const uint PTYPE_ANY		= 0;
```
Comment (asfernandes) [inline src/include/firebird/FirebirdInterface.idl:737]: Method is `getType`, so why `PTYPE_` instead of `TYPE_`?
The names are already at scope `Provider`.
We don't use the extra specifications in the others constants.

File: src/yvalve/why.cpp [hunk 3]
```diff
@@ -6515,83 +6553,122 @@ YService* Dispatcher::attachServiceManager(CheckStatusWrapper* status, const cha
 			IntlSpb().toUtf8(spbWriter);
 		}
 
-		// Build correct config
-		RefPtr<const Config> config(Config::getDefaultConfig());
-		if (spbWriter.find(isc_spb_config))
+		IProvider* p;
+		service = internalServiceAttach(status, svcName, spbWriter,
+			[](CheckStatusWrapper*, IService*){ }, Dispatcher::PTYPE_ANY, &p);
```
Comment (asfernandes) [inline src/yvalve/why.cpp:6558]: Can't this empty lambda be just `{}`?

File: src/yvalve/why.cpp (hunk 1 above)
Comment (AlexPeshkoff) [reply src/yvalve/why.cpp:6343]: I suppose you talk about client (i.e. embedded usage)? Or also about FB4 server on non-default port (XNET disabled) and FB3 on default port (XNET enabled)? 

First case formally works (provided one is using services for engine13 embedded access which actually makes no sense). 

Second will work only when Redirection=1 in firebird.conf. But for single server with default network setup that will cause infinite recursion, even when no additional providers present, Redirection=1 is enough. Something not good.

Looks like good alternative to avoid recursion is to cleanup Redirection at all. That will avoid need in getType(), enable first case (at client) and reliably protect from infinite recursion.

File: src/yvalve/why.cpp (hunk 3 above)
Comment (AlexPeshkoff) [reply src/yvalve/why.cpp:6558]: Can - but I see no use in it, in that case additional null check in internalServiceAttach() needed.

File: src/include/firebird/FirebirdInterface.idl (hunk 2 above)
Comment (AlexPeshkoff) [reply src/include/firebird/FirebirdInterface.idl:737]: I will fix it - provided this method does not go away at all after "Redirection" cleanup.

File: src/yvalve/why.cpp (hunk 1 above)
Comment (AlexPeshkoff) [reply src/yvalve/why.cpp:6343]: See devel (Redirection parameter in firebird.conf) - why additionally pollute code supporting generally useless feature?
