### PR TITLE
Fixed bug #8885 : AV when lock manager settings is misconfigured.

### LINKED ISSUE #8885: AV when lock manager settings is misconfigured
It is possible to set lock manager params in firebird.conf (databases.conf) to overflow initial memory segment during initialization.

For example, set in firebird.conf
```
LockMemSize = 256K
LockHashSlots = 65521
```
and connect to any database.

<details><summary>Call stack</summary>
<p>

```
engine13.dll!Jrd::LockManager::initialize Line 2329
	at fb50\src\lock\lock.cpp(2329)
engine13.dll!Firebird::SharedMemoryBase::SharedMemoryBase Line 1885
	at fb50\src\common\isc_sync.cpp(1885)
[Inline Frame] engine13.dll!Firebird::SharedMemory<lhb>::{ctor} Line 344
	at fb50\src\common\isc_s_proto.h(344)
engine13.dll!Jrd::LockManager::init_shared_file Line 302
	at fb50\src\lock\lock.cpp(302)
engine13.dll!Jrd::LockManager::LockManager Line 188
	at fb50\src\lock\lock.cpp(188)
engine13.dll!Jrd::Database::GlobalObjectHolder::getLockManager Line 697
	at fb50\src\jrd\Database.cpp(697)
[Inline Frame] engine13.dll!Jrd::Database::lockManager Line 689
	at fb50\src\jrd\Database.h(689)
engine13.dll!LCK_init Line 637
	at fb50\src\jrd\lck.cpp(637)
engine13.dll!Jrd::JProvider::internalAttach Line 1818
	at fb50\src\jrd\jrd.cpp(1818)
engine13.dll!Jrd::JProvider::attachDatabase Line 1624
	at fb50\src\jrd\jrd.cpp(1624)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by hvlad**
Ensure shared memory size is multiply of system page size - it guarantees mapObject() will not access area after the end of file. 
It could fix #5860 : operating system directive MapViewOfFile failed access denied [CORE5594]

### CODE REVIEW

File: src/lock/lock.cpp [hunk 1]
```diff
@@ -177,11 +177,26 @@ LockManager::LockManager(const string& id, const Config* conf)
...
+		m_hashSlots = HASH_MAX_SLOTS;
+
+	// memory size required to fit all hash slots, history blocks and header blocks
+	const auto minMemory = sizeof(lhb) +
+		FB_ALIGN(sizeof(shb), FB_ALIGNMENT) +
+		sizeof(lhb::lhb_hash[0]) * m_hashSlots +
+		FB_ALIGN(sizeof(his), FB_ALIGNMENT) * HISTORY_BLOCKS * 2;
+
+	if (m_memorySize < minMemory)
+		m_memorySize = minMemory;
```
Comment (dyemanov) [inline src/lock/lock.cpp:198]: Shouldn't `minMemory` be aligned to the memory page boundary before assignment to `m_memorySize`?

Comment (hvlad) [reply src/lock/lock.cpp:198]: Such alignment made in `SharedMemoryBase` ctor - it allows to not modify all and every shmem user and to not expose `SharedMemoryBase` internal details (requirements).

**Review by dyemanov — APPROVED** [review]

File: src/lock/lock.cpp (hunk 1 above)
Comment (hvlad) [reply src/lock/lock.cpp:198]: Also, note, there is no guarantee that user-configured value of `m_memorySize` is aligned properly.

File: src/common/isc_sync.cpp [hunk 2]
```diff
@@ -1286,6 +1312,17 @@ SharedMemoryBase::SharedMemoryBase(const TEXT* filename, ULONG length, IpcObject
...
+	if (length)
+	{
+		sh_mem_increment = FB_ALIGN(length, getSystemPageSize(&statusVector));
+
+		if (statusVector.hasData())
+			status_exception::raise(&statusVector);
+
+		if (length < sh_mem_increment)
+			length = sh_mem_increment;
+	}
```
Comment (AlexPeshkoff) [inline src/common/isc_sync.cpp:1321]: As far as I can see here `length` will be aligned only when it's less then `sh_mem_increment`. Why not do 

`length = FB_ALIGN(length, getSystemPageSize(&statusVector));`

instead ?

**Review by AlexPeshkoff — CHANGES_REQUESTED** [review]

File: src/common/isc_sync.cpp (hunk 2 above)
Comment (hvlad) [reply src/common/isc_sync.cpp:1321]: It will change nothing, i.e. result is the same. But I agree - the code is not very clear.

**Review by AlexPeshkoff — APPROVED** [review]
